name: Deploy Webpage

on:
  push:
    branches: [migration-to-github] # TODO change to main when it is working

  # workflow_dispatch:
  #     inputs:
  #       logLevel:
  #         description: 'Log level'
  #         required: true
  #         default: 'warning'
  #       tags:
  #         description: 'Test scenario tags'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     registry-url: https://npm.pkg.github.com/
      #     scope: "@jaimemartinmartin15"
      # - name: Install
      #   run: npm ci --no-audit --no-fund
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
      # - name: Generate icons
      #   run: |
      #     mkdir -p src/svg/generated
      #     npm run icons
      # - name: Build
      #   run: npm run build
      # - name: Set AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1-node16
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # - name: Deploy
      #   run: |
      #     aws --version
      #     aws s3 sync ./dist/jaimeelingeniero s3://jaimeelingeniero.es --delete
      - name: Create new tag
        run: |
          git config --global user.email "jaimemartinmartin15@gmail.com"
          git config --global user.name "Jaime Martín Martín"
          git tag -a 1.0.0 -m ""
          git push origin --tags